import { Header } from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TextProvider } from "@/providers/textProvider";
import { FetchProvider } from "@/providers/FetchProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "convert.io | imagem em texto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <TextProvider>
          <FetchProvider>
            {children}
          </FetchProvider>
        </TextProvider>
      </body>
    </html>
  );
}
